### ISSUE TITLE
Bokeh line plot is just a constant

### ISSUE THREAD

**Issue by nbren12** [nbren12/geostreams#11]
I have tried rerunning the demo we did, but the bokeh line plot is just a constant function. Here is screenshot of from my laptop:
![](https://i.imgur.com/Ebtabg6.png)

@jhamman

**Comment by jhamman** [comment]
Not sure what is happening here. When the redis get function times out, we return an array of zeros but I'd expect boty the left and right plots to show zeros.

**Comment by nbren12** [comment]
I think this was resolved by updating bokeh. closing.
