### ISSUE TITLE
Use same environmental variable for storing redis password, host, and port

### ISSUE THREAD

**Issue by nbren12** [nbren12/geostreams#3]
It is `PASS` in `src/redis_wrapper.c` and `REDIS_PW` in `src/client.py`. I think the latter is probably better. We should also probably have `REDIS_URL` and `REDIS_PORT` variables as well.

**Comment by phargogh** [comment]
I'll update the python files to use the environment variables `REDIS_PW`, `REDIS_URL` and `REDIS_PORT` instead of the defaults.

**Comment by nbren12** [comment]
I also changed to using this env variables in `redis_wrapper.c`. I forgot which commit this was though, but I think this issue is resolved.
